ProyectoTesis/Models/Movement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProyectoTesis.Models
{
    public enum MovementType
    {
        Compra = 1, Pérdida = 2, Hallazgo = 3, Despacho = 4
    }

    public class Movement
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un producto")]
        [Display(Name = "Producto")]
        public int ProductID { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Vencimiento")]
        public DateTime? ExpirationDate { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha del Movimiento")]
        public DateTime? MovementDate { get; set; }
        [Display(Name = "Zona")]
        public int ZoneID { get; set; }
        [Display(Name = "Tipo de Movimiento")]
        public MovementType MovementType { get; set; }
        [Display(Name = "Cantidad de Cajas")]
        public int BoxUnits { get; set; }
        [Display(Name = "Cantidad de Fracciones")]
        public int FractionUnits { get; set; }
        [Display(Name = "Documento de Referencia")]
        public int? DocumentID { get; set; }

        [Display(Name = "Producto")]
        public virtual Product Product { get; set; }
        [Display(Name = "Zona")]
        public virtual Zone Zone { get; set; }
        [Display(Name = "Activo?")]
        public bool ActiveFlag { get; set; }
        [ForeignKey("DocumentID")]
        public virtual Document Document { get; set; }
    }
}

ProyectoTesis/Controllers/MovementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTesis.DAL;
using ProyectoTesis.Models;
using PagedList;

namespace ProyectoTesis.Controllers
{
    public class MovementController : Controller
    {
        private StoreContext db = new StoreContext();

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        string user = DAL.GlobalVariables.CurrentUser;

        // GET: Movement
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DescriptionSortParam = sortOrder == "Description" ? "description_desc" : "Description";
            ViewBag.MovementDateSortParam = String.IsNullOrEmpty(sortOrder) ? "movementDate_desc" : "";
            ViewBag.MovementDateSortParam = sortOrder == "Document" ? "document_desc" : "Document";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var movements = db.Movements.Include(m => m.Product).Include(m => m.Zone);

            if (!String.IsNullOrEmpty(searchString))
            {
                movements = movements.Where(m => (m.Product.Description.Contains(searchString) || m.MovementType.ToString().Contains(searchString)) && m.ActiveFlag == false);
            }

            switch (sortOrder)
            {
                case "document_desc":
                    movements = movements.OrderByDescending(m => m.DocumentID);
                    break;
                case "Document":
                    movements = movements.OrderBy(m => m.DocumentID);
                    break;
                case "description_desc":
                    movements = movements.OrderByDescending(m => m.Product.Description);
                    break;
                case "movementDate_desc":
                    movements = movements.OrderByDescending(m => m.MovementDate);
                    break;
                case "Description":
                    movements = movements.OrderBy(m => m.Product.Description);
                    break;
                default:
                    movements = movements.OrderBy(m => m.MovementDate);
                    break;
            }
            int pageSize = 15;
            int pageNumber = (page ?? 1);

            return View(movements.ToPagedList(pageNumber, pageSize));
        }

        // GET: Movement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movement movement = db.Movements.Find(id);
            if (movement == null)
            {
                return HttpNotFound();
            }
            return View(movement);
        }

        // GET: Movement/Create
        public ActionResult Create()
        {
            ViewBag.DocumentID = new SelectList(db.Documents.Where(s => s.ActiveFlag == false), "ID", "ID");
            ViewBag.ProductID = new SelectList(db.Products.Where(s => s.ActiveFlag == true), "ID", "Description");
            ViewBag.ZoneID = new SelectList(db.Zones.Where(s => s.ActiveFlag == false), "ID", "Description");
            return View();
        }

        // POST: Movement/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductID,ExpirationDate,ZoneID,MovementType,BoxUnits,FractionUnits,DocumentID")] Movement movement)
        {
            if (ModelState.IsValid)
            {
                db.Movements.Add(movement);
                Product product = db.Products.Find(movement.ProductID);
                double quantity = movement.BoxUnits + (movement.FractionUnits / product.FractionUnits);
                if(movement.MovementType == MovementType.Compra || movement.MovementType == MovementType.Hallazgo)
                {
                    product.PhysicalStock += quantity;
                    product.LogicalStock += quantity;
                }else if(movement.MovementType == MovementType.Despacho || movement.MovementType == MovementType.Pérdida){
                    product.PhysicalStock -= quantity;
                    product.LogicalStock -= quantity;
                }
                db.SaveChanges();
                log.Info("El usuario " + user + " creó un movimiento con ID: " + movement.ID + " para el producto: " + db.Products.Find(movement.ProductID).Description + " de tipo: " + movement.MovementType.ToString()); return RedirectToAction("Index");
            }

            ViewBag.DocumentID = new SelectList(db.Documents.Where(s => s.ActiveFlag == false), "ID", "ID", movement.DocumentID);
            ViewBag.ProductID = new SelectList(db.Products.Where(s => s.ActiveFlag == true), "ID", "Description", movement.ProductID);
            ViewBag.ZoneID = new SelectList(db.Zones.Where(s => s.ActiveFlag == false), "ID", "Description", movement.ZoneID);
            return View(movement);
        }

        // GET: Movement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movement movement = db.Movements.Find(id);
            if (movement == null)
            {
                return HttpNotFound();
            }
            ViewBag.DocumentID = new SelectList(db.Documents.Where(s => s.ActiveFlag == false), "ID", "ID", movement.DocumentID);
            ViewBag.ProductID = new SelectList(db.Products.Where(s => s.ActiveFlag == true), "ID", "Description", movement.ProductID);
            ViewBag.ZoneID = new SelectList(db.Zones.Where(s => s.ActiveFlag == false), "ID", "Description", movement.ZoneID);
            return View(movement);
        }

        // POST: Movement/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductID,ExpirationDate,ZoneID,MovementType,BoxUnits,FractionUnits,DocumentID")] Movement movement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movement).State = EntityState.Modified;
                db.SaveChanges();
                log.Info("El usuario " + user + " editó un movimiento con ID: " + movement.ID + " para el producto: " + db.Products.Find(movement.ProductID).Description + " de tipo: " + movement.MovementType.ToString()); return RedirectToAction("Index");
            }
            ViewBag.DocumentID = new SelectList(db.Documents.Where(s => s.ActiveFlag == false), "ID", "ID", movement.DocumentID);
            ViewBag.ProductID = new SelectList(db.Products.Where(s => s.ActiveFlag == true), "ID", "Description", movement.ProductID);
            ViewBag.ZoneID = new SelectList(db.Zones.Where(s => s.ActiveFlag == false), "ID", "Description", movement.ZoneID);
            return View(movement);
        }

        // GET: Movement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movement movement = db.Movements.Find(id);
            if (movement == null)
            {
                return HttpNotFound();
            }
            return View(movement);
        }

        // POST: Movement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movement movement = db.Movements.Find(id);
            log.Info("El usuario " + user + " eliminó un movimiento con ID: " + movement.ID + " para el producto: " + db.Products.Find(movement.ProductID).Description + " de tipo: " + movement.MovementType.ToString()); movement.ActiveFlag = true;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void CrearMovimiento(MovementType type, int purchaseOrderID, DateTime expirationDate, int boxes, int fractions, int zoneID, int productID)
        {
            db.Movements.Add(new Movement
            {
                MovementType = type,
                DocumentID = purchaseOrderID,
                ExpirationDate = expirationDate,
                BoxUnits = boxes,
                FractionUnits = fractions,
                ZoneID = zoneID,
                ProductID = productID
            });

            Product product = db.Products.Find(productID);
            double quantity = boxes + ((double)fractions / (double)product.FractionUnits);

            if (type == MovementType.Compra || type == MovementType.Hallazgo)
            {
                product.PhysicalStock += quantity;
                product.LogicalStock += quantity;
            }
            else
            {
                product.PhysicalStock -= quantity;
                product.LogicalStock -= quantity;
            }

ProyectoTesis/Views/Movement/Create.cshtml
@model ProyectoTesis.Models.Movement

@{
    ViewBag.Title = "Movimiento - Creación";
}

<h2>Creación de Movimiento</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MovementType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MovementType,
                                          "Seleccionar Tipo de Movimiento", htmlAttributes: new { @class = "form-control", @id = "tipomovimiento" })
                @Html.ValidationMessageFor(model => model.MovementType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "Producto", htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "productlabel" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, "Seleccionar Producto", htmlAttributes: new { @class = "form-control hidden", @id = "product" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "expdatelabel" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control hidden datepicker", @id = "expdate", Value = DateTime.Now } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneID, "Zona", htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "zonelabel" })
            <div class="col-md-10">
                @Html.DropDownList("ZoneID", null, "Seleccionar Zona", htmlAttributes: new { @class = "form-control hidden", @id = "zone" })
                @Html.ValidationMessageFor(model => model.ZoneID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BoxUnits, htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "boxunitslabel" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BoxUnits, new { htmlAttributes = new { @class = "form-control hidden", @id = "boxunits" } })
                @Html.ValidationMessageFor(model => model.BoxUnits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FractionUnits, htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "fractionunitslabel" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FractionUnits, new { htmlAttributes = new { @class = "form-control hidden", @id = "fractionunits" } })
                @Html.ValidationMessageFor(model => model.FractionUnits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentID, "Documento", htmlAttributes: new { @class = "control-label col-md-2 hidden", @id = "documentlabel" })
            <div class="col-md-10">
                @Html.DropDownList("DocumentID", null, "Seleccionar Documento", htmlAttributes: new { @class = "form-control hidden", @id = "document" })
                @Html.ValidationMessageFor(model => model.DocumentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
    @Html.ActionLink("Regresar", "Index")
}

<div>
</div>
    


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/Scripts/jquery.validate.min.js")
        @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
        @Scripts.Render("~/Scripts/moment.js")
        <script type="text/javascript" src="/scripts/jquery.ui.datepicker-sp.js"></script>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/moment.js"></script>
        <script src="~/Scripts/jquery.validate.date.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-3.1.1.min.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#tipomovimiento").change(function (evt) {
                    var id = $("#tipomovimiento").val();

                    if ($("#expdatelabel").hasClass("hidden") == false) $("#expdatelabel").addClass("hidden");
                    if ($("#expdate").hasClass("hidden") == false) $("#expdate").addClass("hidden");
                    if ($("#documentlabel").hasClass("hidden") == false) $("#documentlabel").addClass("hidden");
                    if ($("#document").hasClass("hidden") == false) $("#document").addClass("hidden");

                    $("#productlabel").removeClass("hidden");
                    $("#product").removeClass("hidden");
                    $("#boxunitslabel").removeClass("hidden");
                    $("#boxunits").removeClass("hidden");
                    $("#fractionunitslabel").removeClass("hidden");
                    $("#fractionunits").removeClass("hidden");
                    $("#zonelabel").removeClass("hidden");
                    $("#zone").removeClass("hidden");

                    if (id == 1) {                   
                        $("#expdatelabel").removeClass("hidden");
                        $("#expdate").removeClass("hidden"); 
                        $("#documentlabel").removeClass("hidden");
                        $("#document").removeClass("hidden");
                    } else if (id == 4) {
                        $("#documentlabel").removeClass("hidden");
                        $("#document").removeClass("hidden");
                    }
                })
            })

            $(function () {
                $(".datepicker").datepicker({
                });
            });
        
        </script>

}

ProyectoTesis/Views/Movement/Delete.cshtml
@model ProyectoTesis.Models.Movement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Document.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zone.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zone.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovementType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovementType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BoxUnits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BoxUnits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FractionUnits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FractionUnits)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoTesis/Views/Movement/Details.cshtml
@model ProyectoTesis.Models.Movement

@{
    ViewBag.Title = "Movimientos - Detalles";
}

<h2>Detalle de Movimiento</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Document.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zone.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zone.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate, "{0:dd/MM/yyyy}")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovementType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovementType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BoxUnits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BoxUnits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FractionUnits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FractionUnits)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Regresar", "Index")
</p>

ProyectoTesis/Views/Movement/Index.cshtml
@model PagedList.IPagedList<ProyectoTesis.Models.Movement>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Movimientos";
}

<h2>Movimientos de Almacén</h2>

<p>
    @Html.ActionLink("Nuevo", "Create")
</p>

@using (Html.BeginForm("Index", "Movement", FormMethod.Get))
{
    <p>
        Buscar: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Buscar" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Documento", "Index", new { sortOrder = ViewBag.DocumentSortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Descripción", "Index", new { sortOrder = ViewBag.DescriptionSortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Tipo de Movimiento
        </th>
        <th>
            Cajas
        </th>
        <th>
            Fracciones
        </th>
        <th>
            @Html.ActionLink("Fecha", "Index", new { sortOrder = ViewBag.MovementDateSortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Document.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovementType)
        </td>
        <td>
            @if (item.MovementType == ProyectoTesis.Models.MovementType.Despacho || item.MovementType == ProyectoTesis.Models.MovementType.Pérdida)
            {
                <span>-</span>
            }
            @Html.DisplayFor(modelItem => item.BoxUnits)
        </td>
        <td>
            @if (item.MovementType == ProyectoTesis.Models.MovementType.Despacho || item.MovementType == ProyectoTesis.Models.MovementType.Pérdida)
            {
                <span>-</span>
            }
            @Html.DisplayFor(modelItem => item.FractionUnits)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovementDate)
        </td>
        <td>
            @if (item.MovementType == ProyectoTesis.Models.MovementType.Compra || item.MovementType == ProyectoTesis.Models.MovementType.Despacho)
                {
                <a href = "@Url.Action("Details", new { id = item.ID })" ><i class="fa fa-eye"></i></a>
                }
                else
                {            
                <a href="@Url.Action("Edit", new { id = item.ID })"><i class="fa fa-pencil"></i></a> 
                <a href="@Url.Action("Details", new { id = item.ID })"> | <i class="fa fa-eye"></i></a>
                <a href="@Url.Action("Delete", new { id = item.ID })"> | <i class="fa fa-trash"></i></a>
                }
        </td>
    </tr>
}

</table>

<br />
Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))