ProyectoTesis/Models/PurchasePlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoTesis.Models
{
    public class PurchasePlan
    {
        public int ID { get; set; }
        [Display(Name = "Fecha de Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BeginDate { get; set; }
        [IsDateAfterAttribute("BeginDate", true, ErrorMessage = "La Fecha Fin debe ser mayor a la Fecha de Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Fin")]
        public DateTime EndDate { get; set; }
        [Display(Name = "Activo?")]
        public bool ActiveFlag { get; set; }
        [Display(Name = "Inversión")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Investment { get; set; }

        [Display(Name = "Beneficio Total")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double TotalBenefit
        {
            get
            {
                double totalBenefit = 0.0;
                if (PurchasePlanDetails != null)
                {
                    foreach (PurchasePlanDetail detail in PurchasePlanDetails)
                    {
                        totalBenefit += detail.Benefit;
                    }
                }
                return totalBenefit;
            }
        }

        public virtual ICollection<PurchasePlanDetail> PurchasePlanDetails { get; set; }
    }
}

ProyectoTesis/Controllers/PurchasePlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTesis.DAL;
using ProyectoTesis.Models;
using System.ComponentModel.DataAnnotations;

namespace ProyectoTesis.Controllers
{
    public class PurchasePlanController : Controller
    {
        private StoreContext db = new StoreContext();

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        string user = DAL.GlobalVariables.CurrentUser;

        private double A = 0.1;

        private int[] ProductsID;

        private List<double> CARAMELO = new List<double>(new double[] { 0.06, 0.05, 0.06, 0.12, 0.07, 0.1, 0.09, 0.1, 0.1, 0.13, 0.11, 0.15 });
        private List<double> GALLETA = new List<double>(new double[] {0.09, 0.07, 0.1, 0.12, 0.1, 0.08, 0.11, 0.11, 0.08, 0.1, 0.09, 0.09});
        private List<double> CHOCOLATE = new List<double>(new double[] {0.05, 0.09, 0.06, 0.16, 0.12, 0.1, 0.1, 0.12, 0.08, 0.11, 0.06, 0.1});
        private List<double> CHICLE = new List<double>(new double[] {0.08, 0.06, 0.13, 0.11, 0.1, 0.09, 0.08, 0.1, 0.12, 0.09, 0.1, 0.08});
        private List<double> SNACK = new List<double>(new double[] {0.12, 0.17, 0.11, 0.08, 0.13, 0.04, 0.09, 0.09, 0.09, 0.12, 0.07, 0.03});
        private List<double> BARRA_ENERGETICA = new List<double>(new double[] { 0.01, 0.03, 0.07, 0.17, 0.1, 0.15, 0.04, 0.28, 0.05, 0.1, 0.05, 0.09 });
        private List<double> GOMA = new List<double>(new double[] {0.03, 0.06, 0.05, 0.09, 0.08, 0.1, 0.08, 0.09, 0.14, 0.08, 0.07, 0.27});
        private List<double> GASEOSA = new List<double>(new double[] {0.17, 0.16, 0.02, 0.34, 0.11, 0.05, 0, 0.05, 0, 0, 0.08, 0.17});
        private List<double> MARSHMALLOW = new List<double>(new double[] {0.06, 0.04, 0.09, 0.08, 0.12, 0.11, 0.12, 0.13, 0.08, 0.11, 0.09, 0.09});
        private List<double> WAFER = new List<double>(new double[] {0.03, 0.04, 0.09, 0.09, 0.09, 0.13, 0.1, 0.12, 0.06, 0.11, 0.1, 0.18});
        private List<double> CHUPETE = new List<double>(new double[] {0.04, 0.04, 0.09, 0.09, 0.08, 0.13, 0.07, 0.11, 0.11, 0.13, 0.09, 0.16});
        private List<double> PANETON = new List<double>(new double[] {0.12, 0.02, 0.07, 0, 0, 0.03, 0, 0, 0.1, 0.2, 0.18, 0.44});
        private List<double> CEREAL = new List<double>(new double[] {0.05, 0.04, 0.15, 0.13, 0.12, 0.08, 0.05, 0.12, 0.14, 0.08, 0.1, 0.08});
        private List<double> YOGURT = new List<double>(new double[] {1.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        private List<double> FRUNA = new List<double>(new double[] {0.08, 0.09, 0.1, 0.11, 0.1, 0.08, 0.09, 0.11, 0.08, 0.13, 0.08, 0.08});
        private List<double> TOFFEE = new List<double>(new double[] {0.07, 0.05, 0.08, 0.13, 0.06, 0.06, 0.1, 0.16, 0.18, 0.07, 0.07, 0.12});
        private List<double> BIZCOCHO = new List<double>(new double[] {0.01, 0.05, 0.06, 0.11, 0.06, 0.12, 0.15, 0.09, 0.08, 0.13, 0.13, 0.15});
        private List<double> AGUA = new List<double>(new double[] {0.46, 0.39, 0.04, 0, 0, 0, 0, 0, 0, 0, 0.07, 0.21});
        private List<double> JUGO = new List<double>(new double[] {0.09, 0.14, 0.03, 0.17, 0.13, 0, 0, 0.16, 0.11, 0, 0.14, 0.19});
        private List<double> GELATINA = new List<double>(new double[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.2});


        // GET: PurchasePlan
        public ActionResult Index()
        {
            return View(db.PurchasePlans.ToList());
        }

        // GET: PurchasePlan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchasePlan purchasePlan = db.PurchasePlans.Find(id);
            if (purchasePlan == null)
            {
                return HttpNotFound();
            }
            ViewBag.Details = new List<PurchasePlanDetail>(db.PurchasePlanDetails.Where(p => p.PurchasePlanID == id && (p.BoxUnits >= 0 && p.FractionUnits >= 0)));
            return View(purchasePlan);
        }

        // GET: PurchasePlan/Create
        public ActionResult Create()
        {
            ViewBag.Products = db.Products.ToList(); 
            return View();
        }

        // POST: PurchasePlan/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(string button1, string button2, [Bind(Include = "ID,BeginDate, EndDate,Investment")] PurchasePlan purchasePlan)
        {
            if (ModelState.IsValid)
            {
                db.PurchasePlans.Add(purchasePlan);
                db.SaveChanges();
                int ID = db.PurchasePlans.OrderByDescending(p => p.ID).FirstOrDefault().ID;

                if (button2 != null)
                {
                    return RedirectToAction("ChooseProducts", new { beginDate = purchasePlan.BeginDate, endDate = purchasePlan.EndDate, investment = purchasePlan.Investment, id = ID });
                }
                else
                {
                    List<Product> products = db.Products.Where(p => p.ActiveFlag).ToList();
                    Algorithm(products, purchasePlan.BeginDate, purchasePlan.EndDate, purchasePlan.Investment, ID);
                    return RedirectToAction("Details", new { id = ID });
                }
                log.Info("El usuario " + user + " ejecutó la simulación del plan de compra desde: " + purchasePlan.BeginDate + " hasta: " + purchasePlan.EndDate);

            }
            return View(purchasePlan);
        }



        public ActionResult Plan(int ID, int[] productID)
        {
            int i = 1;
            if (productID != null)
            {
                List<Product> products = new List<Product>();

                foreach (int product in productID)
                {
                    products.Add(db.Products.Where(p => p.ID == product).FirstOrDefault());
                }
                PurchasePlan purchasePlan = db.PurchasePlans.Where(p => p.ID == ID).FirstOrDefault();
                Algorithm(products, purchasePlan.BeginDate, purchasePlan.EndDate, purchasePlan.Investment, ID);

                return RedirectToAction("Details", new { id = ID });
            }
            return View();
        }

        public ActionResult ChooseProducts(DateTime beginDate, DateTime endDate, double investment, int ID, string currentFilter, string searchString)
        {
            List<double> MaxBox = MaxBoxes(db.Products.Where(p => p.ActiveFlag == true).ToList(), beginDate, endDate);
            List<double> LastMonth = LastPeriod(db.Products.Where(p => p.ActiveFlag == true).ToList(), beginDate, endDate);
            List<Product> Products = db.Products.Where(p => p.ActiveFlag == true).OrderBy(p => p.Description).ToList();

            List<ProductPlan> ProductPlan = new List<ProductPlan>();

            int i = 0;

            foreach (Product product in Products)
            {
                ProductPlan.Add(new ProductPlan
                {
                    LastPeriod = LastMonth[i],
                    MaxBoxes = MaxBox[i],
                    Product = product
                });
                i++;
            }

            ViewBag.BeginDate = beginDate;
            ViewBag.EndDate = endDate;
            ViewBag.Investment = investment;

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.ProductPlans = ProductPlan.Where(p => p.Product.Description.Contains(searchString.ToUpper())).ToList();
            }
            else
            {
                ViewBag.ProductPlans = ProductPlan;
            }

            ViewBag.ID = ID;

            return View();
        }

        public List<double> MaximunBoxesQuantity(List<Product> products, DateTime beginDate)
        {
            List<double> maximunQuantity = new List<double>();
            DateTime end;
            
            int i = 0;
            int beginMonth = beginDate.Month, beginDay = beginDate.Day, endMonth, endDay;
            int fractionUnits;
            int productID;
            int maxBoxes = 0, maxFractions = 0;
            ProductType type;
            int months = 0;

            foreach (Product product in products)
            {
                months = 0;
                fractionUnits = product.FractionUnits;
                productID = product.ID;
                type = product.ProductType;
                var month = db.ExpirationTimes.Where(e => e.ProductType == type).FirstOrDefault().Months;
                if (month != null) months = month;
                end = beginDate;
                endDay = end.Day;
                endMonth = end.Month;

                var boxes = db.Movements.Where(m => m.ProductID == productID && ((m.MovementDate.Value.Month == beginMonth && m.MovementDate.Value.Day >= beginDay) ||
                                                                    (m.MovementDate.Value.Month > beginMonth)) &&
                                                                    ((m.MovementDate.Value.Month < endMonth) || (m.MovementDate.Value.Day <= endDay && m.MovementDate.Value.Month == endMonth)) && m.MovementType == MovementType.Despacho).Select(m => m.BoxUnits).DefaultIfEmpty(0).Sum();

                var fractions = db.Movements.Where(m => m.ProductID == productID && ((m.MovementDate.Value.Month == beginMonth && m.MovementDate.Value.Day >= beginDay) ||
                                                                    (m.MovementDate.Value.Month > beginMonth)) &&

ProyectoTesis/Views/PurchasePlan/ChooseProducts.cshtml
@model IEnumerable<ProyectoTesis.Controllers.PurchasePlanController.ProductPlan>

<br />
@using (Html.BeginForm("ChooseProducts", "PurchasePlan", FormMethod.Get))
{
    <p>
        @Html.Hidden("BeginDate")
        @Html.Hidden("EndDate")
        @Html.Hidden("Investment")
        Buscar: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        
        <input type="submit" value="Buscar" />
    </p>
}

<br />
<table class="table">
    <tr>
        <th><input type="checkbox" id="checkAll" /></th>
        <th>
            Producto
        </th>
        <th>
            Stock Actual
        </th>
        <th>
            Cajas Vendidas el Período Anterior
        </th>
        <th>
            Cajas Vendidas Años Anteriores
        </th>
    </tr>

@foreach (var item in (IEnumerable<ProyectoTesis.Controllers.PurchasePlanController.ProductPlan>)ViewBag.ProductPlans) {
    <tr>
        <td>
            <input type="checkbox" class="checkBox" value="@item.Product.ID" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.LogicalStock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastPeriod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxBoxes)
        </td>
    </tr>
}

</table>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10 create">
        <input value="Crear" class="btn btn-default" id="plan"/>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval");

    
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {

            $("#checkAll").click(function () {
                $(".checkBox").prop('checked',
                    $(this).prop('checked'));
            });

            $("#plan").click(function () {
                var selectedIDs = new Array();
                $('input:checkbox.checkBox').each(function () {
                    if ($(this).prop('checked')) {
                        selectedIDs.push($(this).val());
                    }
                });

                $.ajax(
                    {
                        type: "POST",
                        url: "/PurchasePlan/Plan",
                        data: {
                            ID: @ViewBag.ID, productID: selectedIDs
                        },
                        function (result) {
                            window.location.href = "/PurchasePlan/Index";
                        }
                    });
                //window.location.href = "/PurchasePlan/Index";
            });

        });
    </script>
}

ProyectoTesis/Views/PurchasePlan/Create.cshtml
@model ProyectoTesis.Models.PurchasePlan
@using ProyectoTesis.Models;

@{
    ViewBag.Title = "Plan de Compra - Creación";
}

<h2>Creación de Plan de Compra</h2>

@using (Html.BeginForm("Create", "PurchasePlan", FormMethod.Post, new { @class = "purchaseplan" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control date-picker", @id = "fechaInicio" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control date-picker", @id = "fechaFin"} })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Investment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Investment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Investment, "", new { @class = "text-danger" })
            </div>
        </div>
               


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 create">
                <input type="submit" value="Crear" name="button1" class="btn btn-default" id="crear" />
                <input type="submit" value="Escoger Productos" name="button2" class="btn btn-info" />
                @*@Html.ActionLink(
                "Escoger Productos",
                "Create", 
                "PurchasePlan", 
                new { purchasePlan = Model, type = 1 }, 
                new { @type ="submit", @class = "btn btn-info" })*@
                @*<input type="button" value="Escoger Productos" class="btn btn-default" onclick="location.href='@Url.Action("Create", "PurchasePlan")?type=1"/>*@
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

<div class="loading" align="center">
    Procesando. Por favor, espere.<br />
    <br />
    <img src="~/Content/ajax-loader.gif" alt="" />
</div>


<style type="text/css">
    .modal {
        position: fixed;
        top: 0;
        left: 0;
        background-color: black;
        z-index: 99;
        opacity: 0.8;
        filter: alpha(opacity=80);
        opacity: 0.8;
        min-height: 100%;
        width: 100%;
    }

    .loading {
        font-family: Arial;
        font-size: 10pt;
        border: 5px solid #67CFF5;
        width: 250px;
        height: 150px;
        display: none;
        position: fixed;
        background-color: White;
        z-index: 999;
    }
</style>



@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/moment.js")*@
    @*<script src="~/Scripts/moment.js"></script>*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    @*<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />*@
    @*<script src="~/Scripts/jquery-3.2.1.min.js"></script>*@
    @*<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>*@

    <script type="text/javascript">
        function ShowProgress() {
            setTimeout(function () {
                var modal = $('<div />');
                modal.addClass("modal");
                $('body').append(modal);
                var loading = $(".loading");
                loading.show();
                var top = Math.max($(window).height() / 2 - loading[0].offsetHeight / 2, 0);
                var left = Math.max($(window).width() / 2 - loading[0].offsetWidth / 2, 0);
                loading.css({ top: top, left: left });
            }, 200);
        }
    </script>
    <script type="text/javascript">

        $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '< Ant',
            nextText: 'Sig >',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['es']);

        $(function () {
            $('#fechaInicio').datepicker({
            });
        });

        $(function () {
            $('#fechaFin').datepicker({
            });
        });

</script>
}

ProyectoTesis/Views/PurchasePlan/Delete.cshtml
@model ProyectoTesis.Models.PurchasePlan

@{
    ViewBag.Title = "Plan de Compra - Eliminación";
}

<h2>Eliminar Plan de Compra</h2>

<h3>¿Está seguro que desea eliminar éste plan de compra?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Investment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Investment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

ProyectoTesis/Views/PurchasePlan/Details.cshtml
@model ProyectoTesis.Models.PurchasePlan
    @using ProyectoTesis.Models

@{
    ViewBag.Title = "Plan de Compra - Detalle";
}

<h2>Detalle de Plan de Compra</h2>

<table class="table">
    <tr>
        <th>
            Producto
        </th>
        <th>
            Cajas
        </th>
        <th>
            Fracciones
        </th>
        <th>
            Beneficio
        </th>
        <th></th>
    </tr>

    @foreach (var item in (List<PurchasePlanDetail>)ViewBag.Details)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BoxUnits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FractionUnits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Benefit)
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Regresar", "Index")
</p>

ProyectoTesis/Views/PurchasePlan/Edit.cshtml
@model ProyectoTesis.Models.PurchasePlan

@{
    ViewBag.Title = "Plan de Compra - Edición";
}

<h2>Editar Plan de Compra</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Investment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Investment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Investment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/Scripts/moment.js")
    <script type="text/javascript" src="/scripts/jquery.ui.datepicker-sp.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/jquery.validate.date.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script type="text/javascript">
        $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '< Ant',
            nextText: 'Sig >',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['es']);

        $(function () {
            $('.datepicker').datepicker({
            });
        });
    </script>
}

ProyectoTesis/Views/PurchasePlan/Index.cshtml
@model IEnumerable<ProyectoTesis.Models.PurchasePlan>

@{
    ViewBag.Title = "Plan de Compra";
}

<h2>Planes de Compra</h2>

<p>
    @Html.ActionLink("Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BeginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Investment)
        </th>
        <th>
            Beneficio Total
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BeginDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Investment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalBenefit)
        </td>
        <td>
            <a href="@Url.Action("Details", "PurchasePlan", new { id = item.ID, PurchaseOrderID = ViewBag.PurchaseOrder})"><i class="fa fa-eye"></i></a> |
            <a href="@Url.Action("Delete", "PurchasePlan", new { id = item.ID, PurchaseOrderID = ViewBag.PurchaseOrder})"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
}

</table>